export default [
  'AKUTANSI',
  'MANAJEMEN',
  'ADMINISTRASI BISNIS',
  'ADMINISTRASI PUBLIK',
  'HUKUM',
  'ILMU KOMUNIKASI',
  'INFORMATIKA',
  'PENDIDIKAN BAHASA INGGRIS',
  'SISTEM INFORMASI',
  'ARSITEKTUR',
  'TEKNIK MESIN',
  'TEKNIK SIPIL'
]
